# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('likes', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('coefficient', models.IntegerField()),
                ('sub_category', models.CharField(max_length=400)),
                ('main_category', models.CharField(max_length=400)),
                ('ml_out', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
