# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0003_auto_20180401_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts_data',
        ),
    ]
