# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0005_posts_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts_data',
        ),
    ]
