# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dmm', '0006_delete_posts_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts_data',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('likes', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('coefficient', models.FloatField()),
                ('ml_out', models.IntegerField()),
                ('url', models.TextField()),
            ],
        ),
    ]
