# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0007_posts_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_model', models.CharField(max_length=100, verbose_name='Main Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_model', models.CharField(max_length=100, verbose_name='Sub-Category')),
                ('main_category_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmm.Main_Category')),
            ],
        ),
    ]
