# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0008_main_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts_data',
            name='user_url',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
